apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "ch.configmap" . | nindent 2 }}
data:
  index.html: |-
    {
      "chart": "{{ .Chart.Name }}",
      "version": "{{ .Chart.Version }}"
      "releaseName": "{{ .Release.Name }}"
      "appVersion": "{{ .Chart.AppVersion }}"
    }
