helm:
	helm package charts/CH1 -d packages && \
	helm package charts/CH2 -d packages && \
	helm package charts/CH3 -d packages && \
	helm package charts/CH4 -d packages && \
	helm package charts/CH5 -d packages && \
	helm package charts/CH6 -d packages && \
	helm package charts/CH7 -d packages && \
	helm package charts/CH8 -d packages && \
	helm package charts/CH9 -d packages && \
	helm package charts/CH10 -d packages && \
	helm package charts/CH11 -d packages && \
	helm package charts/CH12 -d packages && \
	helm package charts/CH13 -d packages && \
	helm package charts/CH14 -d packages && \
	helm package charts/CH15 -d packages && \
	helm package charts/CH16 -d packages && \
	helm package charts/CH17 -d packages && \
	helm package charts/CH18 -d packages && \
	helm package charts/CH19 -d packages && \
	helm package charts/CH20 -d packages && \
	helm package charts/CH21 -d packages && \
	helm package charts/CH22 -d packages && \
	helm package charts/CH23 -d packages && \
	helm package charts/CH24 -d packages && \
	helm package charts/CH25 -d packages && \
	helm package charts/CH26 -d packages && \
	helm package charts/CH27 -d packages && \
	helm package charts/CH28 -d packages && \
	helm package charts/CH29 -d packages && \
	helm package charts/CH30 -d packages && \
	helm package charts/CH31 -d packages && \
	helm package charts/CH32 -d packages && \
	helm package charts/CH33 -d packages && \
	helm package charts/CH34 -d packages && \
	helm package charts/CH35 -d packages && \
	helm package charts/CH36 -d packages && \
	helm package charts/CH37 -d packages && \
	helm package charts/CH38 -d packages && \
	helm package charts/CH39 -d packages && \
	helm package charts/CH40 -d packages && \
	helm package charts/CH41 -d packages && \
	helm package charts/CH42 -d packages && \
	helm package charts/CH43 -d packages && \
	helm package charts/CH44 -d packages && \
	helm package charts/CH45 -d packages && \
	helm package charts/CH46 -d packages && \
	helm package charts/CH47 -d packages && \
	helm package charts/CH48 -d packages && \
	helm package charts/CH49 -d packages && \
	helm package charts/CH50 -d packages && \
	helm package charts/CH51 -d packages && \
	helm package charts/CH52 -d packages && \
	helm package charts/CH53 -d packages && \
	helm package charts/CH54 -d packages && \
	helm package charts/CH55 -d packages && \
	helm package charts/CH56 -d packages && \
	helm package charts/CH57 -d packages && \
	helm package charts/CH58 -d packages && \
	helm package charts/CH59 -d packages && \
	helm package charts/CH60 -d packages && \
	helm package charts/CH61 -d packages && \
	helm package charts/CH62 -d packages && \
	helm package charts/CH63 -d packages && \
	helm package charts/CH64 -d packages && \
	helm package charts/CH65 -d packages && \
	helm package charts/CH66 -d packages && \
	helm package charts/CH67 -d packages && \
	helm package charts/CH68 -d packages && \
	helm package charts/CH69 -d packages && \
	helm package charts/CH70 -d packages && \
	helm package charts/CH71 -d packages && \
	helm package charts/CH72 -d packages && \
	helm package charts/CH73 -d packages && \
	helm package charts/CH74 -d packages && \
	helm package charts/CH75 -d packages && \
	helm package charts/CH76 -d packages && \
	helm package charts/CH77 -d packages && \
	helm package charts/CH78 -d packages && \
	helm package charts/CH79 -d packages && \
	helm package charts/CH80 -d packages && \
	helm package charts/CH81 -d packages && \
	helm package charts/CH82 -d packages && \
	helm package charts/CH83 -d packages && \
	helm package charts/CH84 -d packages && \
	helm package charts/CH85 -d packages && \
	helm package charts/CH86 -d packages && \
	helm package charts/CH87 -d packages && \
	helm package charts/CH88 -d packages && \
	helm package charts/CH89 -d packages && \
	helm package charts/CH90 -d packages && \
	helm package charts/CH91 -d packages && \
	helm package charts/CH92 -d packages && \
	helm package charts/CH93 -d packages && \
	helm package charts/CH94 -d packages && \
	helm package charts/CH95 -d packages && \
	helm package charts/CH96 -d packages && \
	helm package charts/CH97 -d packages && \
	helm package charts/CH98 -d packages && \
	helm package charts/CH99 -d packages && \
	helm package charts/CH100 -d packages && \
	helm repo index --url https://github.com/nicholasSUSE/mapps-helm-test .