helm:
	helm package charts/CH1 -d packages && \
	helm package charts/CH2 -d packages && \
	helm package charts/CH3 -d packages && \
	helm package charts/CH4 -d packages && \
	helm package charts/CH5 -d packages && \
	helm package charts/CH6 -d packages && \
	helm package charts/CH7 -d packages && \
	helm package charts/CH8 -d packages && \
	helm package charts/CH9 -d packages && \
	helm package charts/CH10 -d packages && \
	helm package charts/CH11 -d packages && \
	helm package charts/CH12 -d packages && \
	helm package charts/CH13 -d packages && \
	helm package charts/CH14 -d packages && \
	helm package charts/CH15 -d packages && \
	helm package charts/CH16 -d packages && \
	helm package charts/CH17 -d packages && \
	helm package charts/CH18 -d packages && \
	helm package charts/CH19 -d packages && \
	helm package charts/CH20 -d packages && \
	helm package charts/CH21 -d packages && \
	helm package charts/CH22 -d packages && \
	helm package charts/CH23 -d packages && \
	helm package charts/CH24 -d packages && \
	helm package charts/CH25 -d packages && \
	helm package charts/CH26 -d packages && \
	helm package charts/CH27 -d packages && \
	helm package charts/CH28 -d packages && \
	helm package charts/CH29 -d packages && \
	helm package charts/CH30 -d packages && \
	helm package charts/CH31 -d packages && \
	helm package charts/CH32 -d packages && \
	helm package charts/CH33 -d packages && \
	helm package charts/CH34 -d packages && \
	helm package charts/CH35 -d packages && \
	helm package charts/CH36 -d packages && \
	helm package charts/CH37 -d packages && \
	helm package charts/CH38 -d packages && \
	helm package charts/CH39 -d packages && \
	helm package charts/CH40 -d packages && \
	helm package charts/CH41 -d packages && \
	helm package charts/CH42 -d packages && \
	helm package charts/CH43 -d packages && \
	helm package charts/CH44 -d packages && \
	helm package charts/CH45 -d packages && \
	helm package charts/CH46 -d packages && \
	helm package charts/CH47 -d packages && \
	helm package charts/CH48 -d packages && \
	helm package charts/CH49 -d packages && \
	helm package charts/CH50 -d packages && \
	helm package charts/CH51 -d packages && \
	helm package charts/CH52 -d packages && \
	helm package charts/CH53 -d packages && \
	helm package charts/CH54 -d packages && \
	helm package charts/CH55 -d packages && \
	helm package charts/CH56 -d packages && \
	helm package charts/CH57 -d packages && \
	helm package charts/CH58 -d packages && \
	helm package charts/CH59 -d packages && \
	helm package charts/CH60 -d packages && \
	helm package charts/CH61 -d packages && \
	helm package charts/CH62 -d packages && \
	helm package charts/CH63 -d packages && \
	helm package charts/CH64 -d packages && \
	helm package charts/CH65 -d packages && \
	helm package charts/CH66 -d packages && \
	helm package charts/CH67 -d packages && \
	helm package charts/CH68 -d packages && \
	helm package charts/CH69 -d packages && \
	helm package charts/CH70 -d packages && \
	helm package charts/CH71 -d packages && \
	helm package charts/CH72 -d packages && \
	helm package charts/CH73 -d packages && \
	helm package charts/CH74 -d packages && \
	helm package charts/CH75 -d packages && \
	helm package charts/CH76 -d packages && \
	helm package charts/CH77 -d packages && \
	helm package charts/CH78 -d packages && \
	helm package charts/CH79 -d packages && \
	helm package charts/CH80 -d packages && \
	helm package charts/CH81 -d packages && \
	helm package charts/CH82 -d packages && \
	helm package charts/CH83 -d packages && \
	helm package charts/CH84 -d packages && \
	helm package charts/CH85 -d packages && \
	helm package charts/CH86 -d packages && \
	helm package charts/CH87 -d packages && \
	helm package charts/CH88 -d packages && \
	helm package charts/CH89 -d packages && \
	helm package charts/CH90 -d packages && \
	helm package charts/CH91 -d packages && \
	helm package charts/CH92 -d packages && \
	helm package charts/CH93 -d packages && \
	helm package charts/CH94 -d packages && \
	helm package charts/CH95 -d packages && \
	helm package charts/CH96 -d packages && \
	helm package charts/CH97 -d packages && \
	helm package charts/CH98 -d packages && \
	helm package charts/CH99 -d packages && \
	helm package charts/CH100 -d packages && \
	helm package charts/CH101 -d packages && \
	helm package charts/CH102 -d packages && \
	helm package charts/CH103 -d packages && \
	helm package charts/CH104 -d packages && \
	helm package charts/CH105 -d packages && \
	helm package charts/CH106 -d packages && \
	helm package charts/CH107 -d packages && \
	helm package charts/CH108 -d packages && \
	helm package charts/CH109 -d packages && \
	helm package charts/CH110 -d packages && \
	helm package charts/CH111 -d packages && \
	helm package charts/CH112 -d packages && \
	helm package charts/CH113 -d packages && \
	helm package charts/CH114 -d packages && \
	helm package charts/CH115 -d packages && \
	helm package charts/CH116 -d packages && \
	helm package charts/CH117 -d packages && \
	helm package charts/CH118 -d packages && \
	helm package charts/CH119 -d packages && \
	helm package charts/CH120 -d packages && \
	helm package charts/CH121 -d packages && \
	helm package charts/CH122 -d packages && \
	helm package charts/CH123 -d packages && \
	helm package charts/CH124 -d packages && \
	helm package charts/CH125 -d packages && \
	helm package charts/CH126 -d packages && \
	helm package charts/CH127 -d packages && \
	helm package charts/CH128 -d packages && \
	helm package charts/CH129 -d packages && \
	helm package charts/CH130 -d packages && \
	helm package charts/CH131 -d packages && \
	helm package charts/CH132 -d packages && \
	helm package charts/CH133 -d packages && \
	helm package charts/CH134 -d packages && \
	helm package charts/CH135 -d packages && \
	helm package charts/CH136 -d packages && \
	helm package charts/CH137 -d packages && \
	helm package charts/CH138 -d packages && \
	helm package charts/CH139 -d packages && \
	helm package charts/CH140 -d packages && \
	helm package charts/CH141 -d packages && \
	helm package charts/CH142 -d packages && \
	helm package charts/CH143 -d packages && \
	helm package charts/CH144 -d packages && \
	helm package charts/CH145 -d packages && \
	helm package charts/CH146 -d packages && \
	helm package charts/CH147 -d packages && \
	helm package charts/CH148 -d packages && \
	helm package charts/CH149 -d packages && \
	helm package charts/CH150 -d packages && \
	helm package charts/CH151 -d packages && \
	helm package charts/CH152 -d packages && \
	helm package charts/CH153 -d packages && \
	helm package charts/CH154 -d packages && \
	helm package charts/CH155 -d packages && \
	helm package charts/CH156 -d packages && \
	helm package charts/CH157 -d packages && \
	helm package charts/CH158 -d packages && \
	helm package charts/CH159 -d packages && \
	helm package charts/CH160 -d packages && \
	helm package charts/CH161 -d packages && \
	helm package charts/CH162 -d packages && \
	helm package charts/CH163 -d packages && \
	helm package charts/CH164 -d packages && \
	helm package charts/CH165 -d packages && \
	helm package charts/CH166 -d packages && \
	helm package charts/CH167 -d packages && \
	helm package charts/CH168 -d packages && \
	helm package charts/CH169 -d packages && \
	helm package charts/CH170 -d packages && \
	helm package charts/CH171 -d packages && \
	helm package charts/CH172 -d packages && \
	helm package charts/CH173 -d packages && \
	helm package charts/CH174 -d packages && \
	helm package charts/CH175 -d packages && \
	helm package charts/CH176 -d packages && \
	helm package charts/CH177 -d packages && \
	helm package charts/CH178 -d packages && \
	helm package charts/CH179 -d packages && \
	helm package charts/CH180 -d packages && \
	helm package charts/CH181 -d packages && \
	helm package charts/CH182 -d packages && \
	helm package charts/CH183 -d packages && \
	helm package charts/CH184 -d packages && \
	helm package charts/CH185 -d packages && \
	helm package charts/CH186 -d packages && \
	helm package charts/CH187 -d packages && \
	helm package charts/CH188 -d packages && \
	helm package charts/CH189 -d packages && \
	helm package charts/CH190 -d packages && \
	helm package charts/CH191 -d packages && \
	helm package charts/CH192 -d packages && \
	helm package charts/CH193 -d packages && \
	helm package charts/CH194 -d packages && \
	helm package charts/CH195 -d packages && \
	helm package charts/CH196 -d packages && \
	helm package charts/CH197 -d packages && \
	helm package charts/CH198 -d packages && \
	helm package charts/CH199 -d packages && \
	helm package charts/CH200 -d packages && \
	helm repo index --url https://github.com/nicholasSUSE/mapps-helm-test .