helm:
	helm package charts/CH1 -d packages && \
	helm package charts/CH2 -d packages && \
	helm package charts/CH3 -d packages && \
	helm package charts/CH4 -d packages && \
	helm package charts/CH5 -d packages && \
	helm package charts/CH6 -d packages && \
	helm package charts/CH7 -d packages && \
	helm package charts/CH8 -d packages && \
	helm package charts/CH9 -d packages && \
	helm package charts/CH10 -d packages && \
	helm package charts/CH11 -d packages && \
	helm package charts/CH12 -d packages && \
	helm package charts/CH13 -d packages && \
	helm package charts/CH14 -d packages && \
	helm package charts/CH15 -d packages && \
	helm package charts/CH16 -d packages && \
	helm package charts/CH17 -d packages && \
	helm package charts/CH18 -d packages && \
	helm package charts/CH19 -d packages && \
	helm package charts/CH20 -d packages && \
	helm package charts/CH21 -d packages && \
	helm package charts/CH22 -d packages && \
	helm package charts/CH23 -d packages && \
	helm package charts/CH24 -d packages && \
	helm package charts/CH25 -d packages && \
	helm package charts/CH26 -d packages && \
	helm package charts/CH27 -d packages && \
	helm package charts/CH28 -d packages && \
	helm package charts/CH29 -d packages && \
	helm package charts/CH30 -d packages && \
	helm package charts/CH31 -d packages && \
	helm package charts/CH32 -d packages && \
	helm package charts/CH33 -d packages && \
	helm package charts/CH34 -d packages && \
	helm package charts/CH35 -d packages && \
	helm package charts/CH36 -d packages && \
	helm package charts/CH37 -d packages && \
	helm package charts/CH38 -d packages && \
	helm package charts/CH39 -d packages && \
	helm package charts/CH40 -d packages && \
	helm package charts/CH41 -d packages && \
	helm package charts/CH42 -d packages && \
	helm package charts/CH43 -d packages && \
	helm package charts/CH44 -d packages && \
	helm package charts/CH45 -d packages && \
	helm package charts/CH46 -d packages && \
	helm package charts/CH47 -d packages && \
	helm package charts/CH48 -d packages && \
	helm package charts/CH49 -d packages && \
	helm package charts/CH50 -d packages && \
	helm package charts/CH51 -d packages && \
	helm package charts/CH52 -d packages && \
	helm package charts/CH53 -d packages && \
	helm package charts/CH54 -d packages && \
	helm package charts/CH55 -d packages && \
	helm package charts/CH56 -d packages && \
	helm package charts/CH57 -d packages && \
	helm package charts/CH58 -d packages && \
	helm package charts/CH59 -d packages && \
	helm package charts/CH60 -d packages && \
	helm package charts/CH61 -d packages && \
	helm package charts/CH62 -d packages && \
	helm package charts/CH63 -d packages && \
	helm package charts/CH64 -d packages && \
	helm package charts/CH65 -d packages && \
	helm package charts/CH66 -d packages && \
	helm package charts/CH67 -d packages && \
	helm package charts/CH68 -d packages && \
	helm package charts/CH69 -d packages && \
	helm package charts/CH70 -d packages && \
	helm package charts/CH71 -d packages && \
	helm package charts/CH72 -d packages && \
	helm package charts/CH73 -d packages && \
	helm package charts/CH74 -d packages && \
	helm package charts/CH75 -d packages && \
	helm package charts/CH76 -d packages && \
	helm package charts/CH77 -d packages && \
	helm package charts/CH78 -d packages && \
	helm package charts/CH79 -d packages && \
	helm package charts/CH80 -d packages && \
	helm package charts/CH81 -d packages && \
	helm package charts/CH82 -d packages && \
	helm package charts/CH83 -d packages && \
	helm package charts/CH84 -d packages && \
	helm package charts/CH85 -d packages && \
	helm package charts/CH86 -d packages && \
	helm package charts/CH87 -d packages && \
	helm package charts/CH88 -d packages && \
	helm package charts/CH89 -d packages && \
	helm package charts/CH90 -d packages && \
	helm package charts/CH91 -d packages && \
	helm package charts/CH92 -d packages && \
	helm package charts/CH93 -d packages && \
	helm package charts/CH94 -d packages && \
	helm package charts/CH95 -d packages && \
	helm package charts/CH96 -d packages && \
	helm package charts/CH97 -d packages && \
	helm package charts/CH98 -d packages && \
	helm package charts/CH99 -d packages && \
	helm package charts/CH100 -d packages && \
	helm package charts/CH101 -d packages && \
	helm package charts/CH102 -d packages && \
	helm package charts/CH103 -d packages && \
	helm package charts/CH104 -d packages && \
	helm package charts/CH105 -d packages && \
	helm package charts/CH106 -d packages && \
	helm package charts/CH107 -d packages && \
	helm package charts/CH108 -d packages && \
	helm package charts/CH109 -d packages && \
	helm package charts/CH110 -d packages && \
	helm package charts/CH111 -d packages && \
	helm package charts/CH112 -d packages && \
	helm package charts/CH113 -d packages && \
	helm package charts/CH114 -d packages && \
	helm package charts/CH115 -d packages && \
	helm package charts/CH116 -d packages && \
	helm package charts/CH117 -d packages && \
	helm package charts/CH118 -d packages && \
	helm package charts/CH119 -d packages && \
	helm package charts/CH120 -d packages && \
	helm package charts/CH121 -d packages && \
	helm package charts/CH122 -d packages && \
	helm package charts/CH123 -d packages && \
	helm package charts/CH124 -d packages && \
	helm package charts/CH125 -d packages && \
	helm package charts/CH126 -d packages && \
	helm package charts/CH127 -d packages && \
	helm package charts/CH128 -d packages && \
	helm package charts/CH129 -d packages && \
	helm package charts/CH130 -d packages && \
	helm package charts/CH131 -d packages && \
	helm package charts/CH132 -d packages && \
	helm package charts/CH133 -d packages && \
	helm package charts/CH134 -d packages && \
	helm package charts/CH135 -d packages && \
	helm package charts/CH136 -d packages && \
	helm package charts/CH137 -d packages && \
	helm package charts/CH138 -d packages && \
	helm package charts/CH139 -d packages && \
	helm package charts/CH140 -d packages && \
	helm package charts/CH141 -d packages && \
	helm package charts/CH142 -d packages && \
	helm package charts/CH143 -d packages && \
	helm package charts/CH144 -d packages && \
	helm package charts/CH145 -d packages && \
	helm package charts/CH146 -d packages && \
	helm package charts/CH147 -d packages && \
	helm package charts/CH148 -d packages && \
	helm package charts/CH149 -d packages && \
	helm package charts/CH150 -d packages && \
	helm package charts/CH151 -d packages && \
	helm package charts/CH152 -d packages && \
	helm package charts/CH153 -d packages && \
	helm package charts/CH154 -d packages && \
	helm package charts/CH155 -d packages && \
	helm package charts/CH156 -d packages && \
	helm package charts/CH157 -d packages && \
	helm package charts/CH158 -d packages && \
	helm package charts/CH159 -d packages && \
	helm package charts/CH160 -d packages && \
	helm package charts/CH161 -d packages && \
	helm package charts/CH162 -d packages && \
	helm package charts/CH163 -d packages && \
	helm package charts/CH164 -d packages && \
	helm package charts/CH165 -d packages && \
	helm package charts/CH166 -d packages && \
	helm package charts/CH167 -d packages && \
	helm package charts/CH168 -d packages && \
	helm package charts/CH169 -d packages && \
	helm package charts/CH170 -d packages && \
	helm package charts/CH171 -d packages && \
	helm package charts/CH172 -d packages && \
	helm package charts/CH173 -d packages && \
	helm package charts/CH174 -d packages && \
	helm package charts/CH175 -d packages && \
	helm package charts/CH176 -d packages && \
	helm package charts/CH177 -d packages && \
	helm package charts/CH178 -d packages && \
	helm package charts/CH179 -d packages && \
	helm package charts/CH180 -d packages && \
	helm package charts/CH181 -d packages && \
	helm package charts/CH182 -d packages && \
	helm package charts/CH183 -d packages && \
	helm package charts/CH184 -d packages && \
	helm package charts/CH185 -d packages && \
	helm package charts/CH186 -d packages && \
	helm package charts/CH187 -d packages && \
	helm package charts/CH188 -d packages && \
	helm package charts/CH189 -d packages && \
	helm package charts/CH190 -d packages && \
	helm package charts/CH191 -d packages && \
	helm package charts/CH192 -d packages && \
	helm package charts/CH193 -d packages && \
	helm package charts/CH194 -d packages && \
	helm package charts/CH195 -d packages && \
	helm package charts/CH196 -d packages && \
	helm package charts/CH197 -d packages && \
	helm package charts/CH198 -d packages && \
	helm package charts/CH199 -d packages && \
	helm package charts/CH200 -d packages && \
	helm package charts/CH201 -d packages && \
	helm package charts/CH202 -d packages && \
	helm package charts/CH203 -d packages && \
	helm package charts/CH204 -d packages && \
	helm package charts/CH205 -d packages && \
	helm package charts/CH206 -d packages && \
	helm package charts/CH207 -d packages && \
	helm package charts/CH208 -d packages && \
	helm package charts/CH209 -d packages && \
	helm package charts/CH210 -d packages && \
	helm package charts/CH211 -d packages && \
	helm package charts/CH212 -d packages && \
	helm package charts/CH213 -d packages && \
	helm package charts/CH214 -d packages && \
	helm package charts/CH215 -d packages && \
	helm package charts/CH216 -d packages && \
	helm package charts/CH217 -d packages && \
	helm package charts/CH218 -d packages && \
	helm package charts/CH219 -d packages && \
	helm package charts/CH220 -d packages && \
	helm package charts/CH221 -d packages && \
	helm package charts/CH222 -d packages && \
	helm package charts/CH223 -d packages && \
	helm package charts/CH224 -d packages && \
	helm package charts/CH225 -d packages && \
	helm package charts/CH226 -d packages && \
	helm package charts/CH227 -d packages && \
	helm package charts/CH228 -d packages && \
	helm package charts/CH229 -d packages && \
	helm package charts/CH230 -d packages && \
	helm package charts/CH231 -d packages && \
	helm package charts/CH232 -d packages && \
	helm package charts/CH233 -d packages && \
	helm package charts/CH234 -d packages && \
	helm package charts/CH235 -d packages && \
	helm package charts/CH236 -d packages && \
	helm package charts/CH237 -d packages && \
	helm package charts/CH238 -d packages && \
	helm package charts/CH239 -d packages && \
	helm package charts/CH240 -d packages && \
	helm package charts/CH241 -d packages && \
	helm package charts/CH242 -d packages && \
	helm package charts/CH243 -d packages && \
	helm package charts/CH244 -d packages && \
	helm package charts/CH245 -d packages && \
	helm package charts/CH246 -d packages && \
	helm package charts/CH247 -d packages && \
	helm package charts/CH248 -d packages && \
	helm package charts/CH249 -d packages && \
	helm package charts/CH250 -d packages && \
	helm package charts/CH251 -d packages && \
	helm package charts/CH252 -d packages && \
	helm package charts/CH253 -d packages && \
	helm package charts/CH254 -d packages && \
	helm package charts/CH255 -d packages && \
	helm package charts/CH256 -d packages && \
	helm package charts/CH257 -d packages && \
	helm package charts/CH258 -d packages && \
	helm package charts/CH259 -d packages && \
	helm package charts/CH260 -d packages && \
	helm package charts/CH261 -d packages && \
	helm package charts/CH262 -d packages && \
	helm package charts/CH263 -d packages && \
	helm package charts/CH264 -d packages && \
	helm package charts/CH265 -d packages && \
	helm package charts/CH266 -d packages && \
	helm package charts/CH267 -d packages && \
	helm package charts/CH268 -d packages && \
	helm package charts/CH269 -d packages && \
	helm package charts/CH270 -d packages && \
	helm package charts/CH271 -d packages && \
	helm package charts/CH272 -d packages && \
	helm package charts/CH273 -d packages && \
	helm package charts/CH274 -d packages && \
	helm package charts/CH275 -d packages && \
	helm package charts/CH276 -d packages && \
	helm package charts/CH277 -d packages && \
	helm package charts/CH278 -d packages && \
	helm package charts/CH279 -d packages && \
	helm package charts/CH280 -d packages && \
	helm package charts/CH281 -d packages && \
	helm package charts/CH282 -d packages && \
	helm package charts/CH283 -d packages && \
	helm package charts/CH284 -d packages && \
	helm package charts/CH285 -d packages && \
	helm package charts/CH286 -d packages && \
	helm package charts/CH287 -d packages && \
	helm package charts/CH288 -d packages && \
	helm package charts/CH289 -d packages && \
	helm package charts/CH290 -d packages && \
	helm package charts/CH291 -d packages && \
	helm package charts/CH292 -d packages && \
	helm package charts/CH293 -d packages && \
	helm package charts/CH294 -d packages && \
	helm package charts/CH295 -d packages && \
	helm package charts/CH296 -d packages && \
	helm package charts/CH297 -d packages && \
	helm package charts/CH298 -d packages && \
	helm package charts/CH299 -d packages && \
	helm package charts/CH300 -d packages && \
	helm package charts/CH301 -d packages && \
	helm package charts/CH302 -d packages && \
	helm package charts/CH303 -d packages && \
	helm package charts/CH304 -d packages && \
	helm package charts/CH305 -d packages && \
	helm package charts/CH306 -d packages && \
	helm package charts/CH307 -d packages && \
	helm package charts/CH308 -d packages && \
	helm package charts/CH309 -d packages && \
	helm package charts/CH310 -d packages && \
	helm package charts/CH311 -d packages && \
	helm package charts/CH312 -d packages && \
	helm package charts/CH313 -d packages && \
	helm package charts/CH314 -d packages && \
	helm package charts/CH315 -d packages && \
	helm package charts/CH316 -d packages && \
	helm package charts/CH317 -d packages && \
	helm package charts/CH318 -d packages && \
	helm package charts/CH319 -d packages && \
	helm package charts/CH320 -d packages && \
	helm package charts/CH321 -d packages && \
	helm package charts/CH322 -d packages && \
	helm package charts/CH323 -d packages && \
	helm package charts/CH324 -d packages && \
	helm package charts/CH325 -d packages && \
	helm package charts/CH326 -d packages && \
	helm package charts/CH327 -d packages && \
	helm package charts/CH328 -d packages && \
	helm package charts/CH329 -d packages && \
	helm package charts/CH330 -d packages && \
	helm package charts/CH331 -d packages && \
	helm package charts/CH332 -d packages && \
	helm package charts/CH333 -d packages && \
	helm package charts/CH334 -d packages && \
	helm package charts/CH335 -d packages && \
	helm package charts/CH336 -d packages && \
	helm package charts/CH337 -d packages && \
	helm package charts/CH338 -d packages && \
	helm package charts/CH339 -d packages && \
	helm package charts/CH340 -d packages && \
	helm package charts/CH341 -d packages && \
	helm package charts/CH342 -d packages && \
	helm package charts/CH343 -d packages && \
	helm package charts/CH344 -d packages && \
	helm package charts/CH345 -d packages && \
	helm package charts/CH346 -d packages && \
	helm package charts/CH347 -d packages && \
	helm package charts/CH348 -d packages && \
	helm package charts/CH349 -d packages && \
	helm package charts/CH350 -d packages && \
	helm package charts/CH351 -d packages && \
	helm package charts/CH352 -d packages && \
	helm package charts/CH353 -d packages && \
	helm package charts/CH354 -d packages && \
	helm package charts/CH355 -d packages && \
	helm package charts/CH356 -d packages && \
	helm package charts/CH357 -d packages && \
	helm package charts/CH358 -d packages && \
	helm package charts/CH359 -d packages && \
	helm package charts/CH360 -d packages && \
	helm package charts/CH361 -d packages && \
	helm package charts/CH362 -d packages && \
	helm package charts/CH363 -d packages && \
	helm package charts/CH364 -d packages && \
	helm package charts/CH365 -d packages && \
	helm package charts/CH366 -d packages && \
	helm package charts/CH367 -d packages && \
	helm package charts/CH368 -d packages && \
	helm package charts/CH369 -d packages && \
	helm package charts/CH370 -d packages && \
	helm package charts/CH371 -d packages && \
	helm package charts/CH372 -d packages && \
	helm package charts/CH373 -d packages && \
	helm package charts/CH374 -d packages && \
	helm package charts/CH375 -d packages && \
	helm package charts/CH376 -d packages && \
	helm package charts/CH377 -d packages && \
	helm package charts/CH378 -d packages && \
	helm package charts/CH379 -d packages && \
	helm package charts/CH380 -d packages && \
	helm package charts/CH381 -d packages && \
	helm package charts/CH382 -d packages && \
	helm package charts/CH383 -d packages && \
	helm package charts/CH384 -d packages && \
	helm package charts/CH385 -d packages && \
	helm package charts/CH386 -d packages && \
	helm package charts/CH387 -d packages && \
	helm package charts/CH388 -d packages && \
	helm package charts/CH389 -d packages && \
	helm package charts/CH390 -d packages && \
	helm package charts/CH391 -d packages && \
	helm package charts/CH392 -d packages && \
	helm package charts/CH393 -d packages && \
	helm package charts/CH394 -d packages && \
	helm package charts/CH395 -d packages && \
	helm package charts/CH396 -d packages && \
	helm package charts/CH397 -d packages && \
	helm package charts/CH398 -d packages && \
	helm package charts/CH399 -d packages && \
	helm package charts/CH400 -d packages && \
	helm package charts/CH401 -d packages && \
	helm package charts/CH402 -d packages && \
	helm package charts/CH403 -d packages && \
	helm package charts/CH404 -d packages && \
	helm package charts/CH405 -d packages && \
	helm package charts/CH406 -d packages && \
	helm package charts/CH407 -d packages && \
	helm package charts/CH408 -d packages && \
	helm package charts/CH409 -d packages && \
	helm package charts/CH410 -d packages && \
	helm package charts/CH411 -d packages && \
	helm package charts/CH412 -d packages && \
	helm package charts/CH413 -d packages && \
	helm package charts/CH414 -d packages && \
	helm package charts/CH415 -d packages && \
	helm package charts/CH416 -d packages && \
	helm package charts/CH417 -d packages && \
	helm package charts/CH418 -d packages && \
	helm package charts/CH419 -d packages && \
	helm package charts/CH420 -d packages && \
	helm package charts/CH421 -d packages && \
	helm package charts/CH422 -d packages && \
	helm package charts/CH423 -d packages && \
	helm package charts/CH424 -d packages && \
	helm package charts/CH425 -d packages && \
	helm package charts/CH426 -d packages && \
	helm package charts/CH427 -d packages && \
	helm package charts/CH428 -d packages && \
	helm package charts/CH429 -d packages && \
	helm package charts/CH430 -d packages && \
	helm package charts/CH431 -d packages && \
	helm package charts/CH432 -d packages && \
	helm package charts/CH433 -d packages && \
	helm package charts/CH434 -d packages && \
	helm package charts/CH435 -d packages && \
	helm package charts/CH436 -d packages && \
	helm package charts/CH437 -d packages && \
	helm package charts/CH438 -d packages && \
	helm package charts/CH439 -d packages && \
	helm package charts/CH440 -d packages && \
	helm package charts/CH441 -d packages && \
	helm package charts/CH442 -d packages && \
	helm package charts/CH443 -d packages && \
	helm package charts/CH444 -d packages && \
	helm package charts/CH445 -d packages && \
	helm package charts/CH446 -d packages && \
	helm package charts/CH447 -d packages && \
	helm package charts/CH448 -d packages && \
	helm package charts/CH449 -d packages && \
	helm package charts/CH450 -d packages && \
	helm package charts/CH451 -d packages && \
	helm package charts/CH452 -d packages && \
	helm package charts/CH453 -d packages && \
	helm package charts/CH454 -d packages && \
	helm package charts/CH455 -d packages && \
	helm package charts/CH456 -d packages && \
	helm package charts/CH457 -d packages && \
	helm package charts/CH458 -d packages && \
	helm package charts/CH459 -d packages && \
	helm package charts/CH460 -d packages && \
	helm package charts/CH461 -d packages && \
	helm package charts/CH462 -d packages && \
	helm package charts/CH463 -d packages && \
	helm package charts/CH464 -d packages && \
	helm package charts/CH465 -d packages && \
	helm package charts/CH466 -d packages && \
	helm package charts/CH467 -d packages && \
	helm package charts/CH468 -d packages && \
	helm package charts/CH469 -d packages && \
	helm package charts/CH470 -d packages && \
	helm package charts/CH471 -d packages && \
	helm package charts/CH472 -d packages && \
	helm package charts/CH473 -d packages && \
	helm package charts/CH474 -d packages && \
	helm package charts/CH475 -d packages && \
	helm package charts/CH476 -d packages && \
	helm package charts/CH477 -d packages && \
	helm package charts/CH478 -d packages && \
	helm package charts/CH479 -d packages && \
	helm package charts/CH480 -d packages && \
	helm package charts/CH481 -d packages && \
	helm package charts/CH482 -d packages && \
	helm package charts/CH483 -d packages && \
	helm package charts/CH484 -d packages && \
	helm package charts/CH485 -d packages && \
	helm package charts/CH486 -d packages && \
	helm package charts/CH487 -d packages && \
	helm package charts/CH488 -d packages && \
	helm package charts/CH489 -d packages && \
	helm package charts/CH490 -d packages && \
	helm package charts/CH491 -d packages && \
	helm package charts/CH492 -d packages && \
	helm package charts/CH493 -d packages && \
	helm package charts/CH494 -d packages && \
	helm package charts/CH495 -d packages && \
	helm package charts/CH496 -d packages && \
	helm package charts/CH497 -d packages && \
	helm package charts/CH498 -d packages && \
	helm package charts/CH499 -d packages && \
	helm package charts/CH500 -d packages && \
	helm repo index --url https://github.com/nicholasSUSE/mapps-helm-test .