apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- include "ch.ingress" . | nindent 2 }}
  labels:
    {{- include "ch.labels" . | nindent 4 }}
spec:
  rules:
  - host: "localhost"
    http:
      paths:
      - pathType: Prefix
        path: "/{{ .Chart.Name }}"
        backend:
          service:
            name: {{ .Release.Name }}--service
            port:
              number: {{ .Values.service.port }}
