apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "ch.nginx" . | nindent 2 }}
  labels:
    {{- include "ch.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen {{ .Values.nginx.listenPort }}; # Use nginx listenPort from values.yaml
      location / {
        return 200 '{"chartName": "{{ .Chart.Name }}", "chartVersion": "{{ .Chart.Version }}", "releaseName": "{{ .Release.Name }}", "appVersion": "{{ .Chart.AppVersion }}"}';
        default_type 'application/json';
      }
    }
