apiVersion: v2
name: ch133
description: ch1 Chart with Ingress + Nginx and automatic job testing
version: 11.0.0
appVersion: "11.0.0"
icon: https://raw.githubusercontent.com/nicholasSUSE/mapps-helm-test/master/icons/ch13.jpg